# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: brian m. bot
email: brian.bot@sagebase.org
description1: open science advocate
description2: community builder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: BrianMBot
github_username:  brian-bot

# Build settings
markdown: kramdown
